# C:\Users\rajku\Downloads\sem 6\AC applied cryptography\projects\PROJECT_SENTINEL_V4\SENTINEL_CBDC_PROJECT\docker\docker-compose.yml

version: '3.8'

services:
  # --- THE VAULT (Database) ---
  sentinel-vault:
    image: postgres:16-alpine
    container_name: sentinel-vault
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_secure_pass
      POSTGRES_DB: sentinel_ledger
    ports:
      - "5433:5432"
    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/seed_data.sql:/docker-entrypoint-initdb.d/seed.sql
      - sentinel-data:/var/lib/postgresql/data
    networks:
      - sentinel-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d sentinel_ledger"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- THE CORE (Rust Backend) ---
  sentinel-core:
    build:
      context: ../core
      dockerfile: ../docker/Dockerfile.backend
    container_name: sentinel-core
    environment:
      DATABASE_URL: postgres://sentinel:sentinel_secure_pass@sentinel-vault:5432/sentinel_ledger
      PORT: 3000
      RUST_LOG: debug
      JWT_SECRET: docker_dev_secret_key_8822
      CAPTCHA_SECRET: docker_dev_captcha_key_9911
    ports:
      - "3000:3000"
      - "9999:9999/udp"
    depends_on:
      sentinel-vault:
        condition: service_healthy
    networks:
      - sentinel-net

  # --- THE FACE (Frontend / Edge Proxy) ---
  sentinel-web:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: sentinel-web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sentinel-core
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge

volumes:
  sentinel-data: